### ISSUE TITLE
execution speed is too slow.

### ISSUE THREAD

**Issue by WinXsp** [bswck/slothy#52]
### Describe the bug

In high-frequency function calls, the speed is 216% slower compared to normal imports.

### To reproduce

execution time: 3.345788 seconds
![_1](https://github.com/bswck/slothy/assets/26323067/e39f1078-b935-46d6-bd07-ac71c688e927)

execution time: 7.239794 seconds
![_2](https://github.com/bswck/slothy/assets/26323067/74b9f652-a8f6-457c-848c-489f3d171241)

### Versions

- OS: windows 11
- Python: python 3.11

**Comment by bswck** [comment]
No snippet in here measures slothy performance. 

```py
with lazy_importing():
    import json

import json
```

imports the json module eagerly.

The execution speed decrease was probably a CPU spike on your end.
